spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pm?createDatabaseIfNotExist=true&useSSL=false
    username: root
  jpa:   
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
